#!/usr/bin/env python3
"""PV-N10: Ordivon Verify — Separated Package Build Artifact Smoke.

Builds wheel/sdist locally from the separated Ordivon Verify package
context (generated by prepare_ordivon_verify_package_context.py).

Inspects artifacts for private core leakage, secret markers, and
public-release overclaims. Reports honestly.

Does not upload, publish, activate license, or call network APIs.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_CONTEXT = ROOT / ".tmp" / "ordivon-verify-package-context"
PREPARE_SCRIPT = ROOT / "scripts" / "prepare_ordivon_verify_package_context.py"
BUILD_OUTPUT = ROOT / ".tmp" / "ordivon-verify-build"

# ── Files/dirs that must NOT appear in a public Ordivon Verify artifact ─
FORBIDDEN_PATHS = [
    "adapters/",
    "domains/",
    "orchestrator/",
    "capabilities/",
    "intelligence/",
    "apps/",
    "policies/",
    "execution/",
    "infra/",
    "state/",
    "services/",
    "docs/governance/",
    "docs/runtime/",
    "docs/ai/",
    "docs/architecture/",
    "docs/product/ordivon-verify-public-repo-",
    "docs/archive/",
    "knowledge/",
    "scripts/smoke_",
    "scripts/eval_",
    "scripts/run_",
    "scripts/dev/",
    "scripts/seed_",
    "tests/contracts/",
    "tests/integration/",
    "tests/e2e/",
]

# ── Files/dirs that SHOULD be in the artifact ─
EXPECTED_PATHS = [
    "ordivon_verify/",
    "schemas/",
]

# ── Unsafe markers (checked in member names, not file content) ──
UNSAFE_NAME_MARKERS = [
    "API_KEY",
    "SECRET",
    "TOKEN",
    "PASSWORD",
    "PRIVATE_KEY",
    "ALPACA",
    "broker",
    "live trading",
    "pfios",
    "aegisos",
]

# ── Unsafe overclaim phrases in README/docs ──
OVERCLAIM_PHRASES = [
    "production-ready",
    "public alpha",
    "published",
    "authorizes execution",
    "approved by Verify",
]


def prepare_context() -> bool:
    """Run the package context generation script. Returns True if OK."""
    r = subprocess.run(
        [sys.executable, str(PREPARE_SCRIPT)],
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(ROOT),
    )
    return r.returncode == 0


def build_from_context() -> dict:
    """Build wheel/sdist from the separated package context. Returns result dict."""
    result = {"wheel_built": False, "sdist_built": False, "wheel_path": None, "sdist_path": None}

    if not PACKAGE_CONTEXT.exists():
        result["build_error"] = "package context not found — run prepare script first"
        return result

    # Clean old build outputs
    dist_dir = PACKAGE_CONTEXT / "dist"
    if dist_dir.exists():
        import shutil

        shutil.rmtree(dist_dir)

    proc = subprocess.run(
        ["uv", "build"],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=str(PACKAGE_CONTEXT),
    )
    if proc.returncode != 0:
        result["build_error"] = proc.stderr[-500:]
        return result

    # Find artifacts
    for f in sorted(dist_dir.glob("*.whl")):
        result["wheel_built"] = True
        result["wheel_path"] = str(f)
    for f in sorted(dist_dir.glob("*.tar.gz")):
        result["sdist_built"] = True
        result["sdist_path"] = str(f)

    return result


def inspect_artifact(path: Path) -> list[str]:
    """List all member names in a wheel or sdist."""
    names: list[str] = []
    if path.suffix == ".whl":
        with zipfile.ZipFile(path) as zf:
            names = zf.namelist()
    elif path.suffix == ".gz" and ".tar" in path.suffixes:
        with tarfile.open(path, "r:gz") as tf:
            names = tf.getnames()
    return names


def find_forbidden(names: list[str]) -> list[str]:
    """Find member names matching forbidden paths."""
    found = []
    for name in names:
        normalized = name.replace("\\", "/")
        for forbidden in FORBIDDEN_PATHS:
            if forbidden.endswith("/"):
                if normalized.startswith(forbidden) or f"/{forbidden}" in normalized:
                    found.append(name)
                    break
                continue
            if normalized.startswith(forbidden) or forbidden in normalized:
                found.append(name)
                break
    return found


def find_expected(names: list[str]) -> list[str]:
    """Find expected paths present. Returns list of expected paths found."""
    present = []
    for expected in EXPECTED_PATHS:
        for name in names:
            if expected in name or name.startswith(expected):
                if expected not in present:
                    present.append(expected)
                break
    return present


def find_unsafe_names(names: list[str]) -> list[str]:
    """Find member names containing unsafe markers."""
    suspicious = []
    for name in names:
        # Red-team fixtures intentionally encode unsafe scenarios in filenames.
        # The audit should catch accidental public-surface leakage, not block
        # negative test cases that prove the checker can reject bad inputs.
        normalized = name.replace("\\", "/")
        if "/fixtures/" in normalized or normalized.startswith("tests/fixtures/"):
            continue
        lower = name.lower()
        for marker in UNSAFE_NAME_MARKERS:
            if marker.lower() in lower:
                suspicious.append(f"{name} (marker: {marker})")
                break
    return suspicious


def scan_artifact_readme(names: list[str], artifact_path: Path) -> list[str]:
    """Scan README or pyproject for overclaim phrases in wheel/sdist."""
    findings = []
    readme_candidates = [
        n for n in names if n.lower().endswith("readme.md") or n == "ordivon_verify-0.1.0.dist-info/METADATA"
    ]
    for candidate in readme_candidates[:1]:  # Just check first README
        if artifact_path.suffix == ".whl":
            with zipfile.ZipFile(artifact_path) as zf:
                try:
                    content = zf.read(candidate).decode(errors="replace")
                except KeyError:
                    continue
        else:
            with tarfile.open(artifact_path, "r:gz") as tf:
                try:
                    f = tf.extractfile(candidate)
                    content = f.read().decode(errors="replace") if f else ""
                except KeyError:
                    continue
        lower = content.lower()
        for phrase in OVERCLAIM_PHRASES:
            ph_lower = phrase.lower()
            if ph_lower in lower:
                # Check for negations within a small window
                idx = lower.index(ph_lower)
                before = lower[max(0, idx - 15) : idx]
                if "not " in before or "no " in before or "not yet " in before:
                    continue
                findings.append(f"overclaim: {phrase} in {candidate}")
    return findings


def main(json_output: bool = False) -> int:
    # Step 1: Prepare context
    if not prepare_context():
        msg = "Package context generation failed"
        if json_output:
            print(json.dumps({"error": msg}))
        else:
            print(f"❌ {msg}")
        return 1

    # Step 2: Build from context
    build = build_from_context()

    if not build["wheel_built"] and not build["sdist_built"]:
        msg = build.get("build_error", "build produced no artifacts")
        # Offline fallback: inspect the separated context tree directly.
        # This keeps the smoke useful in constrained environments where
        # build-system wheels cannot be fetched, while still blocking on
        # private-path leakage or missing package/schema payloads.
        names = [str(p.relative_to(PACKAGE_CONTEXT)) for p in PACKAGE_CONTEXT.rglob("*") if p.is_file()]
        forbidden = find_forbidden(names)
        expected_present = find_expected(names)
        has_ordivon = any("ordivon_verify" in n for n in names)
        unsafe_names = find_unsafe_names(names)
        blocker = bool(forbidden) or bool(unsafe_names) or not has_ordivon or "schemas/" not in expected_present
        if json_output:
            print(
                json.dumps(
                    {
                        "wheel_built": False,
                        "sdist_built": False,
                        "wheel_path": None,
                        "sdist_path": None,
                        "wheel_members": 0,
                        "sdist_members": 0,
                        "forbidden_in_wheel": 0,
                        "forbidden_in_sdist": 0,
                        "ordivon_verify_present": has_ordivon,
                        "expected_present": expected_present,
                        "unsafe_names": len(unsafe_names),
                        "overclaim_findings": 0,
                        "blocked": blocker,
                        "build_error": msg,
                        "disclaimer": "Fallback context scan only (offline build unavailable). No upload. No publish.",
                    },
                    indent=2,
                )
            )
            return 1 if blocker else 0

        print("=" * 60)
        print("ORDIVON VERIFY — SEPARATED PACKAGE BUILD SMOKE")
        print("=" * 60)
        print(f"\n   📦 Context:     {PACKAGE_CONTEXT}")
        print("   📦 Wheel:       N/A (offline fallback)")
        print("   📦 Sdist:       N/A (offline fallback)")
        print(f"   🔍 Forbidden:   {len(forbidden)}")
        print(f"   ✅ Expected:    {expected_present}")
        print(f"   ✅ ordivon_verify: {has_ordivon}")
        print(f"   ⚠️  Unsafe names: {len(unsafe_names)}")
        print("   ⚠️  Build error: offline/network unavailable; used context scan")
        print(f"\n{'=' * 60}")
        if blocker:
            print("❌ BLOCKED: Context scan found issues.")
            return 1
        print("✅ CLEAN: Context scan passed (schemas/ and ordivon_verify/ present).")
        print("\n   Local build smoke only. No upload. No publish. No public release.")
        return 0

    # Step 3: Inspect
    wheel_names: list[str] = []
    sdist_names: list[str] = []
    if build["wheel_path"]:
        wheel_names = inspect_artifact(Path(build["wheel_path"]))
    if build["sdist_path"]:
        sdist_names = inspect_artifact(Path(build["sdist_path"]))

    forbidden_wheel = find_forbidden(wheel_names)
    forbidden_sdist = find_forbidden(sdist_names or [])
    total_forbidden = len(forbidden_wheel) + len(forbidden_sdist)

    expected_wheel = find_expected(wheel_names)
    has_ordivon = any("ordivon_verify" in n for n in wheel_names)

    unsafe_names = find_unsafe_names(wheel_names)
    if build["sdist_path"]:
        unsafe_names += find_unsafe_names(sdist_names)

    overclaims = scan_artifact_readme(wheel_names, Path(build["wheel_path"])) if build["wheel_path"] else []

    blocker = total_forbidden > 0 or not has_ordivon or len(unsafe_names) > 0 or len(overclaims) > 0

    if json_output:
        print(
            json.dumps(
                {
                    "wheel_built": build["wheel_built"],
                    "sdist_built": build["sdist_built"],
                    "wheel_path": build["wheel_path"],
                    "sdist_path": build["sdist_path"],
                    "wheel_members": len(wheel_names),
                    "sdist_members": len(sdist_names),
                    "forbidden_in_wheel": len(forbidden_wheel),
                    "forbidden_in_sdist": len(forbidden_sdist),
                    "ordivon_verify_present": has_ordivon,
                    "expected_present": expected_wheel,
                    "unsafe_names": len(unsafe_names),
                    "overclaim_findings": len(overclaims),
                    "blocked": blocker,
                    "disclaimer": "Local build only. No upload. No publish.",
                },
                indent=2,
            )
        )
        return 1 if blocker else 0

    # Human output
    print("=" * 60)
    print("ORDIVON VERIFY — SEPARATED PACKAGE BUILD SMOKE")
    print("=" * 60)
    print(f"\n   📦 Context:     {PACKAGE_CONTEXT}")
    print(f"   📦 Wheel:       {build.get('wheel_path', 'N/A')} ({len(wheel_names)} members)")
    print(f"   📦 Sdist:       {build.get('sdist_path', 'N/A')}")
    print(f"   🔍 Forbidden:   {total_forbidden}")
    print(f"   ✅ Expected:    {expected_wheel}")
    print(f"   ✅ ordivon_verify: {has_ordivon}")
    print(f"   ⚠️  Unsafe names: {len(unsafe_names)}")
    print(f"   ⚠️  Overclaims:   {len(overclaims)}")

    if forbidden_wheel:
        print(f"\n   ❌ FORBIDDEN PATHS IN WHEEL ({len(forbidden_wheel)}):")
        unique = sorted(set(f.split("/")[0] for f in forbidden_wheel))
        for u in unique:
            count = sum(1 for f in forbidden_wheel if f.startswith(u))
            print(f"      {u}/ ({count} files)")

    if unsafe_names:
        print(f"\n   ❌ UNSAFE NAME MARKERS ({len(unsafe_names)}):")
        for u in unsafe_names[:10]:
            print(f"      {u}")

    if overclaims:
        print(f"\n   ❌ OVERCLAIMS ({len(overclaims)}):")
        for o in overclaims:
            print(f"      {o}")

    print(f"\n{'=' * 60}")
    if blocker:
        print("❌ BLOCKED: Artifact inspection found issues.")
    else:
        print("✅ CLEAN: No private core, secrets, or overclaims in build artifacts.")
    print("\n   Local build smoke only. No upload. No publish. No public release.")

    return 1 if blocker else 0


if __name__ == "__main__":
    sys.exit(main("--json" in sys.argv))
